export const mockPolicies = [
  {
    id: '1',
    url: 'https://eur-lex.europa.eu/directive/2024/89',
    title: 'EU Data Center Energy Efficiency Directive',
    country: 'European Union',
    region: 'Europe',
    type: 'Directive',
    description: 'Requires data centers to improve energy efficiency by 20% by 2025 and implement waste heat recovery systems.',
    relevanceScore: 9,
    sourceLanguage: 'English',
    effectiveDate: '2025-01-01',
    billNumber: 'DIR-2024/89',
    keyRequirements: ['PUE < 1.4', '20% energy efficiency improvement by 2025', 'Waste heat recovery systems mandatory', 'Annual reporting required'],
    dateAdded: '2025-03-15',
    source: 'EU Commission Directive 2024/89',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2025-03-15-001',
    domainId: 'eu-commission',
    verificationFlags: [],
    referencedPolicies: [],
    referencedUrls: ['https://ec.europa.eu/energy/datacenters'],
    heatLimit: 'PUE < 1.4',
    efficiency: '20% improvement required',
  },
  {
    id: '2',
    url: 'https://www.bundestag.de/bill/2024-512',
    title: 'German Waste Heat Recovery Act',
    country: 'Germany',
    region: 'Europe',
    type: 'Law',
    description: 'Mandates that new data centers above 1MW must implement waste heat recovery and provide heat to local district heating networks.',
    relevanceScore: 9,
    sourceLanguage: 'German',
    effectiveDate: '2024-07-01',
    billNumber: '2024-512',
    keyRequirements: ['Waste heat recovery for facilities >1MW', 'Connection to district heating networks', '60% heat recovery target', 'Compliance reporting every 6 months'],
    dateAdded: '2025-02-20',
    source: 'Bundestag Bill 2024-512',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2025-02-20-003',
    domainId: 'de-bundestag',
    verificationFlags: [],
    referencedPolicies: ['1'],
    referencedUrls: ['https://www.bmwk.de/datacenter-heat'],
    heatLimit: 'Mandatory heat recovery for >1MW',
    efficiency: '60% heat recovery target',
  },
  {
    id: '3',
    url: 'https://www.bca.gov.sg/greenmark/datacenter',
    title: 'Singapore Green Data Centre Standard',
    country: 'Singapore',
    region: 'Asia',
    type: 'Standard',
    description: 'Establishes best practices for tropical climate data centers focusing on cooling efficiency and renewable energy.',
    relevanceScore: 7,
    sourceLanguage: 'English',
    effectiveDate: '2024-04-01',
    billNumber: 'SS-679',
    keyRequirements: ['PUE < 1.3', '80% renewable energy by 2030', 'Advanced cooling systems', 'Annual sustainability reporting'],
    dateAdded: '2025-01-10',
    source: 'Singapore Green Building Council',
    crawlStatus: 'success',
    reviewStatus: 'reviewed',
    scanId: 'scan-2025-01-10-002',
    domainId: 'sg-bca',
    verificationFlags: [],
    referencedPolicies: [],
    referencedUrls: ['https://www.ema.gov.sg/sustainability'],
    heatLimit: 'PUE < 1.3',
    efficiency: '80% renewable energy by 2030',
  },
  {
    id: '4',
    url: 'https://www.energy.ca.gov/title24/datacenter',
    title: 'California Data Center Energy Conservation',
    country: 'United States',
    region: 'North America',
    type: 'Regulation',
    description: 'State-level requirements for data centers to reduce water consumption and implement advanced cooling technologies.',
    relevanceScore: 8,
    sourceLanguage: 'English',
    effectiveDate: '2024-01-01',
    billNumber: 'Title 24-2024',
    keyRequirements: ['WUE < 1.2 L/kWh', 'Free cooling 75% of year', 'Advanced cooling technologies', 'Water consumption reporting'],
    dateAdded: '2024-12-05',
    source: 'CA Energy Commission Title 24',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2024-12-05-001',
    domainId: 'ca-energy',
    verificationFlags: [],
    referencedPolicies: [],
    referencedUrls: ['https://www.cpuc.ca.gov/datacenter'],
    heatLimit: 'WUE < 1.2 L/kWh',
    efficiency: 'Free cooling 75% of year',
  },
  {
    id: '5',
    url: 'https://www.energimyndigheten.se/directive/2024-45',
    title: 'Nordic District Heating Integration Directive',
    country: 'Sweden',
    region: 'Europe',
    type: 'Directive',
    description: 'Requires data centers to integrate with municipal district heating networks and supply waste heat for residential use.',
    relevanceScore: 8,
    sourceLanguage: 'Swedish',
    effectiveDate: '2024-06-01',
    billNumber: 'DIR-2024/45',
    keyRequirements: ['70% minimum heat recovery', 'Connection to district heating networks', 'Heat quality >65°C', 'Quarterly reporting to Energy Agency'],
    dateAdded: '2025-01-15',
    source: 'Swedish Energy Agency Directive 2024/45',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2025-01-15-004',
    domainId: 'se-energy',
    verificationFlags: [],
    referencedPolicies: ['1', '2'],
    referencedUrls: ['https://www.stockholm.se/districthermal'],
    heatLimit: 'Minimum 70% heat recovery',
    efficiency: 'PUE < 1.25',
  },
  {
    id: '6',
    url: 'https://www.metro.tokyo.lg.jp/english/policies/datacenter-2024',
    title: 'Tokyo Green Data Center Incentive Program',
    country: 'Japan',
    region: 'Asia',
    type: 'Incentive',
    description: 'Financial incentives for data centers implementing liquid cooling and waste heat recovery systems in Tokyo metropolitan area.',
    relevanceScore: 7,
    sourceLanguage: 'Japanese',
    effectiveDate: '2024-04-01',
    billNumber: 'TK-2024-156',
    keyRequirements: ['Liquid cooling implementation', 'PUE below 1.3', 'Heat recovery system installation', 'Application with 3-year plan'],
    dateAdded: '2024-11-20',
    source: 'Tokyo Metropolitan Government Grant Program 2024',
    crawlStatus: 'success',
    reviewStatus: 'reviewed',
    scanId: 'scan-2024-11-20-002',
    domainId: 'jp-tokyo',
    verificationFlags: [],
    referencedPolicies: [],
    referencedUrls: ['https://www.env.go.jp/green-energy'],
    heatLimit: 'PUE < 1.3',
    efficiency: 'Up to ¥500M in subsidies',
  },
  {
    id: '7',
    url: 'https://www.belastingdienst.nl/act-2024-88',
    title: 'Netherlands Data Center Heat Recovery Tax Credit',
    country: 'Netherlands',
    region: 'Europe',
    type: 'Tax incentive',
    description: 'Tax credits for data center operators who supply waste heat to greenhouses and residential districts.',
    relevanceScore: 7,
    sourceLanguage: 'Dutch',
    effectiveDate: '2024-01-01',
    billNumber: '2024-88',
    keyRequirements: ['50% minimum heat reuse', 'Contract with greenhouse or district heating', '30% tax credit on investments', 'Annual verification audit'],
    dateAdded: '2025-02-01',
    source: 'Dutch Tax Authority Act 2024-88',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2025-02-01-001',
    domainId: 'nl-tax',
    verificationFlags: [],
    referencedPolicies: ['1'],
    referencedUrls: ['https://www.rvo.nl/subsidies-regelingen/datacenter'],
    heatLimit: 'Minimum 50% heat reuse',
    efficiency: '30% tax credit on heat recovery investments',
  },
  {
    id: '8',
    url: 'https://www.gov.uk/government/publications/datacenter-grant-2024',
    title: 'UK Data Center Energy Efficiency Grant Scheme',
    country: 'United Kingdom',
    region: 'Europe',
    type: 'Grant',
    description: 'Grant funding for retrofitting existing data centers with advanced cooling and heat recovery technologies.',
    relevanceScore: 9,
    sourceLanguage: 'English',
    effectiveDate: '2024-04-01',
    billNumber: 'DESNZ-2024-12',
    keyRequirements: ['PUE improvement to below 1.35', 'Advanced cooling retrofit', 'Heat recovery installation', 'Match funding of 25%'],
    dateAdded: '2024-10-12',
    source: 'UK Department for Energy Security Grant 2024',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2024-10-12-003',
    domainId: 'uk-desnz',
    verificationFlags: [],
    referencedPolicies: ['1'],
    referencedUrls: [],
    heatLimit: 'Target PUE < 1.35',
    efficiency: '£200M grant pool',
  },
  {
    id: '9',
    url: 'https://www.ecologie.gouv.fr/plan-decarbonation-datacenters',
    title: 'French National Data Center Decarbonization Plan',
    country: 'France',
    region: 'Europe',
    type: 'Plan',
    description: 'Strategic roadmap for achieving carbon neutrality in data center operations by 2030 through heat recovery and renewable energy.',
    relevanceScore: 9,
    sourceLanguage: 'French',
    effectiveDate: '2025-01-01',
    billNumber: 'PLAN-2025-2030',
    keyRequirements: ['80% heat recovery by 2030', '100% renewable energy by 2030', 'Annual carbon footprint reporting', 'Integration with local heating networks'],
    dateAdded: '2025-01-08',
    source: 'French Ministry of Digital Transition Plan 2025-2030',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2025-01-08-002',
    domainId: 'fr-ecology',
    verificationFlags: [],
    referencedPolicies: ['1'],
    referencedUrls: ['https://www.ademe.fr/datacenter-energie'],
    heatLimit: '80% waste heat recovery by 2030',
    efficiency: '100% renewable energy by 2030',
  },
  {
    id: '10',
    url: 'https://www.gov.ie/en/publication/datacenter-planning-2024',
    title: 'Ireland Data Center Heat Reuse Requirement',
    country: 'Ireland',
    region: 'Europe',
    type: 'Requirement',
    description: 'Mandatory requirements for new hyperscale data centers to demonstrate viable heat reuse plans before planning approval.',
    relevanceScore: 7,
    sourceLanguage: 'English',
    effectiveDate: '2024-03-01',
    billNumber: 'PA-2024-16',
    keyRequirements: ['Viable heat reuse plan submission', 'PUE below 1.4', 'Community benefit demonstration', 'Environmental impact assessment'],
    dateAdded: '2024-09-18',
    source: 'Irish Planning Authority Requirement 2024',
    crawlStatus: 'success',
    reviewStatus: 'reviewed',
    scanId: 'scan-2024-09-18-001',
    domainId: 'ie-planning',
    verificationFlags: [],
    referencedPolicies: ['1'],
    referencedUrls: [],
    heatLimit: 'Viable heat reuse plan mandatory',
    efficiency: 'PUE < 1.4',
  },
  {
    id: '11',
    url: 'https://www.ds.dk/en/standards/ds-3156',
    title: 'Denmark Technical Standard for Data Center Cooling',
    country: 'Denmark',
    region: 'Europe',
    type: 'Standard',
    description: 'Technical specifications for liquid cooling systems and heat pump integration in Danish data centers.',
    relevanceScore: 7,
    sourceLanguage: 'Danish',
    effectiveDate: '2025-01-01',
    billNumber: 'DS-3156',
    keyRequirements: ['Heat pump COP > 4.0', 'Free cooling 90% of year', 'Liquid cooling specifications', 'Integration with district heating'],
    dateAdded: '2025-03-01',
    source: 'Danish Standards Association DS 3156',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2025-03-01-001',
    domainId: 'dk-standards',
    verificationFlags: [],
    referencedPolicies: ['5'],
    referencedUrls: ['https://ens.dk/datacenter'],
    heatLimit: 'COP > 4.0 for heat pumps',
    efficiency: 'Free cooling 90% of year',
  },
  {
    id: '12',
    url: 'https://www.nrcan.gc.ca/energy-efficiency/datacenter-guide',
    title: 'Canadian Data Center Best Practices Guide',
    country: 'Canada',
    region: 'North America',
    type: 'Guidance',
    description: 'Voluntary guidance for optimizing data center energy efficiency in cold climate regions.',
    relevanceScore: 6,
    sourceLanguage: 'English',
    effectiveDate: '2024-06-01',
    keyRequirements: ['PUE below 1.3 recommended', 'Year-round free cooling', 'Cold climate optimization', 'Heat recovery best practices'],
    dateAdded: '2024-08-25',
    source: 'Natural Resources Canada Publication 2024',
    crawlStatus: 'success',
    reviewStatus: 'reviewed',
    scanId: 'scan-2024-08-25-002',
    domainId: 'ca-nrcan',
    verificationFlags: [],
    referencedPolicies: [],
    referencedUrls: [],
    heatLimit: 'PUE < 1.3 recommended',
    efficiency: 'Year-round free cooling potential',
  },
  {
    id: '13',
    url: 'https://energiavirasto.fi/heat-matching-platform',
    title: 'Finland Heat Network Matching Platform',
    country: 'Finland',
    region: 'Europe',
    type: 'Matching platform',
    description: 'Government platform connecting data center waste heat suppliers with district heating network operators.',
    relevanceScore: 7,
    sourceLanguage: 'Finnish',
    effectiveDate: '2024-09-01',
    keyRequirements: ['Heat quality >60°C', 'Platform registration', 'Quarterly supply reporting', 'Technical compatibility assessment'],
    dateAdded: '2025-02-14',
    source: 'Finnish Energy Authority Platform Initiative',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2025-02-14-003',
    domainId: 'fi-energy',
    verificationFlags: [],
    referencedPolicies: ['5', '11'],
    referencedUrls: ['https://www.helen.fi/datacenter-heat'],
    heatLimit: 'Heat quality >60°C preferred',
    efficiency: 'Facilitates >100MW heat transfer',
  },
  {
    id: '14',
    url: 'https://lis.virginia.gov/cgi-bin/legp604.exe?241+sum+HB2455',
    title: 'Virginia Data Center Energy Performance Law',
    country: 'United States',
    region: 'North America',
    type: 'Law',
    description: 'State law requiring annual energy efficiency reporting and heat recovery feasibility studies for large data centers.',
    relevanceScore: 8,
    sourceLanguage: 'English',
    effectiveDate: '2024-07-01',
    billNumber: 'HB-2455',
    keyRequirements: ['Annual PUE reporting', 'Heat recovery feasibility study', 'Energy consumption disclosure', 'Applies to facilities >5MW'],
    dateAdded: '2024-07-30',
    source: 'Virginia General Assembly Bill HB 2455',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2024-07-30-001',
    domainId: 'us-va-gov',
    verificationFlags: [],
    referencedPolicies: ['4'],
    referencedUrls: [],
    heatLimit: 'Annual reporting required',
    efficiency: 'PUE disclosure mandatory',
  },
  {
    id: '15',
    url: 'https://www.nve.no/datacenter-initiative-2024',
    title: 'Norway Renewable Energy Data Center Initiative',
    country: 'Norway',
    region: 'Europe',
    type: 'Incentive',
    description: 'Subsidies for data centers powered by hydroelectric energy with integrated waste heat recovery systems.',
    relevanceScore: 7,
    sourceLanguage: 'Norwegian',
    effectiveDate: '2024-01-01',
    billNumber: 'NVE-2024-18',
    keyRequirements: ['100% renewable hydroelectric energy', 'Heat recovery system', 'Subsidy application process', 'Minimum 5-year commitment'],
    dateAdded: '2024-12-10',
    source: 'Norwegian Water Resources and Energy Directorate 2024',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2024-12-10-002',
    domainId: 'no-nve',
    verificationFlags: [],
    referencedPolicies: ['5'],
    referencedUrls: ['https://www.enova.no/datacenter'],
    heatLimit: '100% renewable energy required',
    efficiency: 'Up to NOK 100M in subsidies',
  },
  {
    id: '16',
    url: 'https://www.miteco.gob.es/es/rd-2024-92-datacenters.html',
    title: 'Spain Data Center Sustainability Regulation',
    country: 'Spain',
    region: 'Europe',
    type: 'Regulation',
    description: 'Regional regulations for water-scarce areas mandating dry cooling and heat recovery in new data centers.',
    relevanceScore: 7,
    sourceLanguage: 'Spanish',
    effectiveDate: '2024-05-01',
    billNumber: 'RD-2024/92',
    keyRequirements: ['Air cooling in water-scarce zones', 'Heat recovery for desalination', 'Water usage below 0.5 L/kWh', 'Regional compliance certification'],
    dateAdded: '2025-01-22',
    source: 'Spanish Ministry of Ecological Transition RD 2024/92',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2025-01-22-001',
    domainId: 'es-miteco',
    verificationFlags: [],
    referencedPolicies: ['1'],
    referencedUrls: [],
    heatLimit: 'Air cooling mandatory in water-scarce zones',
    efficiency: 'Heat recovery for desalination plants',
  },
  {
    id: '17',
    url: 'https://www.bfe.admin.ch/datacenter-standard-2024',
    title: 'Switzerland Data Center Efficiency Standard',
    country: 'Switzerland',
    region: 'Europe',
    type: 'Standard',
    description: 'National standard for measuring and reporting data center energy efficiency and heat reuse metrics.',
    relevanceScore: 7,
    sourceLanguage: 'German',
    effectiveDate: '2024-01-01',
    billNumber: 'SN-EN-2024',
    keyRequirements: ['PUE below 1.3', 'ERE reporting', 'CUE reporting', 'Annual efficiency audit'],
    dateAdded: '2024-11-05',
    source: 'Swiss Federal Office of Energy Standard SN-EN 2024',
    crawlStatus: 'success',
    reviewStatus: 'reviewed',
    scanId: 'scan-2024-11-05-003',
    domainId: 'ch-bfe',
    verificationFlags: [],
    referencedPolicies: [],
    referencedUrls: [],
    heatLimit: 'PUE < 1.3',
    efficiency: 'ERE and CUE reporting required',
  },
  {
    id: '18',
    url: 'https://environnement.brussels/directive-2025-11',
    title: 'Belgium Data Center Heat Recovery Directive',
    country: 'Belgium',
    region: 'Europe',
    type: 'Directive',
    description: 'Brussels region directive requiring data centers to connect to district heating networks where technically feasible.',
    relevanceScore: 8,
    sourceLanguage: 'French',
    effectiveDate: '2025-01-01',
    billNumber: 'DIR-2025/11',
    keyRequirements: ['Connection within 500m of network', '40% minimum heat recovery', 'Technical feasibility assessment', 'Annual heat supply reporting'],
    dateAdded: '2025-03-10',
    source: 'Brussels Environment Directive 2025/11',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2025-03-10-001',
    domainId: 'be-brussels',
    verificationFlags: [],
    referencedPolicies: ['1', '7'],
    referencedUrls: [],
    heatLimit: 'Connection mandatory within 500m of network',
    efficiency: 'Minimum 40% heat recovery',
  },
  {
    id: '19',
    url: 'https://www.ndrc.gov.cn/datacenter-plan-2024-2029',
    title: 'China National Data Center Energy Plan',
    country: 'China',
    region: 'Asia',
    type: 'Plan',
    description: 'Five-year plan for improving data center energy efficiency and promoting green cooling technologies.',
    relevanceScore: 9,
    sourceLanguage: 'Chinese',
    effectiveDate: '2024-01-01',
    billNumber: 'NDRC-2024-2029',
    keyRequirements: ['PUE below 1.3 for new facilities', '30% efficiency improvement by 2029', 'Green cooling technologies', 'Provincial reporting requirements'],
    dateAdded: '2024-06-15',
    source: 'National Development and Reform Commission Plan 2024-2029',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2024-06-15-002',
    domainId: 'cn-ndrc',
    verificationFlags: ['duplicate_url'],
    referencedPolicies: [],
    referencedUrls: ['https://www.miit.gov.cn/green-datacenter'],
    heatLimit: 'PUE < 1.3 for new facilities',
    efficiency: '30% improvement by 2029',
  },
  {
    id: '20',
    url: 'https://comptroller.texas.gov/taxes/property-tax/exemptions/datacenter',
    title: 'Texas Data Center Energy Efficiency Tax Exemption',
    country: 'United States',
    region: 'North America',
    type: 'Tax incentive',
    description: 'Property tax exemptions for data centers meeting high energy efficiency standards and using renewable energy.',
    relevanceScore: 7,
    sourceLanguage: 'English',
    effectiveDate: '2024-01-01',
    billNumber: 'TX-11.32',
    keyRequirements: ['PUE below 1.4', '50% renewable energy', 'Minimum $250M investment', 'Annual compliance verification'],
    dateAdded: '2024-09-01',
    source: 'Texas Tax Code Section 11.32',
    crawlStatus: 'success',
    reviewStatus: 'reviewed',
    scanId: 'scan-2024-09-01-001',
    domainId: 'us-tx-tax',
    verificationFlags: [],
    referencedPolicies: [],
    referencedUrls: [],
    heatLimit: 'PUE < 1.4',
    efficiency: 'Up to 15-year tax exemption',
  },
  {
    id: '21',
    url: 'https://www.klimafonds.gv.at/datacenter-heat-pump-grant',
    title: 'Austria Data Center Heat Pump Subsidy',
    country: 'Austria',
    region: 'Europe',
    type: 'Grant',
    description: 'Grant program for installing high-temperature heat pumps to upgrade waste heat quality for district heating.',
    relevanceScore: 6,
    sourceLanguage: 'German',
    effectiveDate: '2025-01-01',
    billNumber: 'KLI-2025-07',
    keyRequirements: ['Heat output >70°C', 'High-temperature heat pump', 'Connection to district heating', '40% grant funding'],
    dateAdded: '2025-02-28',
    source: 'Austrian Climate and Energy Fund Grant 2025',
    crawlStatus: 'success',
    reviewStatus: 'reviewed',
    scanId: 'scan-2025-02-28-002',
    domainId: 'at-klimafonds',
    verificationFlags: [],
    referencedPolicies: ['1', '11'],
    referencedUrls: [],
    heatLimit: 'Heat output >70°C',
    efficiency: '€50M grant allocation',
  },
  {
    id: '22',
    url: 'https://nea.is/geothermal-datacenter-guidelines',
    title: 'Iceland Geothermal Data Center Guidelines',
    country: 'Iceland',
    region: 'Europe',
    type: 'Guidance',
    description: 'Best practice guidelines for integrating data center operations with geothermal energy systems.',
    relevanceScore: 6,
    sourceLanguage: 'Icelandic',
    effectiveDate: '2024-04-01',
    keyRequirements: ['100% geothermal energy', 'Natural year-round cooling', 'Integration with geothermal grid', 'Environmental sustainability practices'],
    dateAdded: '2024-10-20',
    source: 'Iceland National Energy Authority Publication 2024',
    crawlStatus: 'success',
    reviewStatus: 'reviewed',
    scanId: 'scan-2024-10-20-001',
    domainId: 'is-nea',
    verificationFlags: ['generic_name'],
    referencedPolicies: ['15'],
    referencedUrls: [],
    heatLimit: 'Natural cooling year-round',
    efficiency: '100% renewable geothermal energy',
  },
  {
    id: '23',
    url: 'https://www.energy.or.kr/smart-datacenter-initiative',
    title: 'South Korea Smart Data Center Initiative',
    country: 'South Korea',
    region: 'Asia',
    type: 'Plan',
    description: 'National initiative promoting AI-optimized cooling and waste heat utilization in data centers.',
    relevanceScore: 7,
    sourceLanguage: 'Korean',
    effectiveDate: '2024-01-01',
    billNumber: 'KEA-2024-2028',
    keyRequirements: ['PUE below 1.3', 'AI-driven cooling optimization', 'Waste heat utilization plan', 'Smart monitoring systems'],
    dateAdded: '2024-08-12',
    source: 'Korea Energy Agency Initiative 2024-2028',
    crawlStatus: 'success',
    reviewStatus: 'verified',
    scanId: 'scan-2024-08-12-003',
    domainId: 'kr-kea',
    verificationFlags: [],
    referencedPolicies: ['3'],
    referencedUrls: ['https://www.motie.go.kr/datacenter'],
    heatLimit: 'PUE < 1.3',
    efficiency: 'AI-driven optimization target',
  },
  {
    id: '24',
    url: 'https://www.ure.gov.pl/datacenter-reporting-2025',
    title: 'Poland Data Center Reporting Requirement',
    country: 'Poland',
    region: 'Europe',
    type: 'Requirement',
    description: 'Mandatory annual reporting of energy consumption, water use, and waste heat recovery rates for data centers over 500kW.',
    relevanceScore: 6,
    sourceLanguage: 'Polish',
    effectiveDate: '2025-01-01',
    billNumber: 'URE-2025-04',
    keyRequirements: ['Annual energy consumption reporting', 'WUE and PUE disclosure', 'Heat recovery rate reporting', 'Applies to facilities >500kW'],
    dateAdded: '2025-01-30',
    source: 'Polish Energy Regulatory Office Requirement 2025',
    crawlStatus: 'success',
    reviewStatus: 'pending',
    scanId: 'scan-2025-01-30-001',
    domainId: 'pl-ure',
    verificationFlags: [],
    referencedPolicies: ['1'],
    referencedUrls: [],
    heatLimit: 'Annual disclosure mandatory',
    efficiency: 'WUE and PUE reporting',
  },
];

export const regions = [
  { id: 'eu', name: 'European Union', continent: 'Europe' },
  {
    id: 'germany',
    name: 'Germany',
    continent: 'Europe',
    children: ['de-bw', 'de-by', 'de-be', 'de-bb', 'de-hb', 'de-hh', 'de-he', 'de-mv', 'de-ni', 'de-nw', 'de-rp', 'de-sl', 'de-sn', 'de-st', 'de-sh', 'de-th']
  },
  { id: 'de-bw', name: 'Baden-Württemberg', continent: 'Europe', parent: 'germany' },
  { id: 'de-by', name: 'Bavaria', continent: 'Europe', parent: 'germany' },
  { id: 'de-be', name: 'Berlin', continent: 'Europe', parent: 'germany' },
  { id: 'de-bb', name: 'Brandenburg', continent: 'Europe', parent: 'germany' },
  { id: 'de-hb', name: 'Bremen', continent: 'Europe', parent: 'germany' },
  { id: 'de-hh', name: 'Hamburg', continent: 'Europe', parent: 'germany' },
  { id: 'de-he', name: 'Hesse', continent: 'Europe', parent: 'germany' },
  { id: 'de-mv', name: 'Mecklenburg-Vorpommern', continent: 'Europe', parent: 'germany' },
  { id: 'de-ni', name: 'Lower Saxony', continent: 'Europe', parent: 'germany' },
  { id: 'de-nw', name: 'North Rhine-Westphalia', continent: 'Europe', parent: 'germany' },
  { id: 'de-rp', name: 'Rhineland-Palatinate', continent: 'Europe', parent: 'germany' },
  { id: 'de-sl', name: 'Saarland', continent: 'Europe', parent: 'germany' },
  { id: 'de-sn', name: 'Saxony', continent: 'Europe', parent: 'germany' },
  { id: 'de-st', name: 'Saxony-Anhalt', continent: 'Europe', parent: 'germany' },
  { id: 'de-sh', name: 'Schleswig-Holstein', continent: 'Europe', parent: 'germany' },
  { id: 'de-th', name: 'Thuringia', continent: 'Europe', parent: 'germany' },
  { id: 'nordic', name: 'Nordic Countries', continent: 'Europe' },
  { id: 'uk', name: 'United Kingdom', continent: 'Europe' },
  { id: 'singapore', name: 'Singapore', continent: 'Asia' },
  { id: 'japan', name: 'Japan', continent: 'Asia' },
  { id: 'china', name: 'China', continent: 'Asia' },
  {
    id: 'us',
    name: 'United States',
    continent: 'North America',
    children: ['us-al', 'us-ak', 'us-az', 'us-ar', 'us-ca', 'us-co', 'us-ct', 'us-de', 'us-fl', 'us-ga', 'us-hi', 'us-id', 'us-il', 'us-in', 'us-ia', 'us-ks', 'us-ky', 'us-la', 'us-me', 'us-md', 'us-ma', 'us-mi', 'us-mn', 'us-ms', 'us-mo', 'us-mt', 'us-ne', 'us-nv', 'us-nh', 'us-nj', 'us-nm', 'us-ny', 'us-nc', 'us-nd', 'us-oh', 'us-ok', 'us-or', 'us-pa', 'us-ri', 'us-sc', 'us-sd', 'us-tn', 'us-tx', 'us-ut', 'us-vt', 'us-va', 'us-wa', 'us-wv', 'us-wi', 'us-wy']
  },
  { id: 'us-al', name: 'Alabama', continent: 'North America', parent: 'us' },
  { id: 'us-ak', name: 'Alaska', continent: 'North America', parent: 'us' },
  { id: 'us-az', name: 'Arizona', continent: 'North America', parent: 'us' },
  { id: 'us-ar', name: 'Arkansas', continent: 'North America', parent: 'us' },
  { id: 'us-ca', name: 'California', continent: 'North America', parent: 'us' },
  { id: 'us-co', name: 'Colorado', continent: 'North America', parent: 'us' },
  { id: 'us-ct', name: 'Connecticut', continent: 'North America', parent: 'us' },
  { id: 'us-de', name: 'Delaware', continent: 'North America', parent: 'us' },
  { id: 'us-fl', name: 'Florida', continent: 'North America', parent: 'us' },
  { id: 'us-ga', name: 'Georgia', continent: 'North America', parent: 'us' },
  { id: 'us-hi', name: 'Hawaii', continent: 'North America', parent: 'us' },
  { id: 'us-id', name: 'Idaho', continent: 'North America', parent: 'us' },
  { id: 'us-il', name: 'Illinois', continent: 'North America', parent: 'us' },
  { id: 'us-in', name: 'Indiana', continent: 'North America', parent: 'us' },
  { id: 'us-ia', name: 'Iowa', continent: 'North America', parent: 'us' },
  { id: 'us-ks', name: 'Kansas', continent: 'North America', parent: 'us' },
  { id: 'us-ky', name: 'Kentucky', continent: 'North America', parent: 'us' },
  { id: 'us-la', name: 'Louisiana', continent: 'North America', parent: 'us' },
  { id: 'us-me', name: 'Maine', continent: 'North America', parent: 'us' },
  { id: 'us-md', name: 'Maryland', continent: 'North America', parent: 'us' },
  { id: 'us-ma', name: 'Massachusetts', continent: 'North America', parent: 'us' },
  { id: 'us-mi', name: 'Michigan', continent: 'North America', parent: 'us' },
  { id: 'us-mn', name: 'Minnesota', continent: 'North America', parent: 'us' },
  { id: 'us-ms', name: 'Mississippi', continent: 'North America', parent: 'us' },
  { id: 'us-mo', name: 'Missouri', continent: 'North America', parent: 'us' },
  { id: 'us-mt', name: 'Montana', continent: 'North America', parent: 'us' },
  { id: 'us-ne', name: 'Nebraska', continent: 'North America', parent: 'us' },
  { id: 'us-nv', name: 'Nevada', continent: 'North America', parent: 'us' },
  { id: 'us-nh', name: 'New Hampshire', continent: 'North America', parent: 'us' },
  { id: 'us-nj', name: 'New Jersey', continent: 'North America', parent: 'us' },
  { id: 'us-nm', name: 'New Mexico', continent: 'North America', parent: 'us' },
  { id: 'us-ny', name: 'New York', continent: 'North America', parent: 'us' },
  { id: 'us-nc', name: 'North Carolina', continent: 'North America', parent: 'us' },
  { id: 'us-nd', name: 'North Dakota', continent: 'North America', parent: 'us' },
  { id: 'us-oh', name: 'Ohio', continent: 'North America', parent: 'us' },
  { id: 'us-ok', name: 'Oklahoma', continent: 'North America', parent: 'us' },
  { id: 'us-or', name: 'Oregon', continent: 'North America', parent: 'us' },
  { id: 'us-pa', name: 'Pennsylvania', continent: 'North America', parent: 'us' },
  { id: 'us-ri', name: 'Rhode Island', continent: 'North America', parent: 'us' },
  { id: 'us-sc', name: 'South Carolina', continent: 'North America', parent: 'us' },
  { id: 'us-sd', name: 'South Dakota', continent: 'North America', parent: 'us' },
  { id: 'us-tn', name: 'Tennessee', continent: 'North America', parent: 'us' },
  { id: 'us-tx', name: 'Texas', continent: 'North America', parent: 'us' },
  { id: 'us-ut', name: 'Utah', continent: 'North America', parent: 'us' },
  { id: 'us-vt', name: 'Vermont', continent: 'North America', parent: 'us' },
  { id: 'us-va', name: 'Virginia', continent: 'North America', parent: 'us' },
  { id: 'us-wa', name: 'Washington', continent: 'North America', parent: 'us' },
  { id: 'us-wv', name: 'West Virginia', continent: 'North America', parent: 'us' },
  { id: 'us-wi', name: 'Wisconsin', continent: 'North America', parent: 'us' },
  { id: 'us-wy', name: 'Wyoming', continent: 'North America', parent: 'us' },
  { id: 'canada', name: 'Canada', continent: 'North America' },
];

export const questionTemplates = [
  {
    id: 'q1',
    template: 'What are the current heat recovery policies for data centers in {region}?',
    category: 'Heat Recovery',
  },
  {
    id: 'q2',
    template: 'What efficiency standards apply to data centers in {region}?',
    category: 'Energy Efficiency',
  },
  {
    id: 'q3',
    template: 'What are the cooling requirements for data centers in {region}?',
    category: 'Cooling Standards',
  },
  {
    id: 'q4',
    template: 'What regulations exist for waste heat utilization in {region}?',
    category: 'Waste Heat',
  },
  {
    id: 'q5',
    template: 'What are the environmental policies for data centers in {region}?',
    category: 'Environmental',
  },
  {
    id: 'q6',
    template: 'What are the PUE requirements for data centers in {region}?',
    category: 'PUE Standards',
  },
  {
    id: 'q7',
    template: 'What renewable energy requirements exist for data centers in {region}?',
    category: 'Renewable Energy',
  },
  {
    id: 'q8',
    template: 'What water usage policies apply to data centers in {region}?',
    category: 'Water Usage',
  },
];

export const mockResponses = {
  'european union': {
    answer: 'The European Union has implemented comprehensive policies for data center heat recovery. The EU Data Center Energy Efficiency Directive requires all new data centers to improve energy efficiency by 20% by 2025 and implement waste heat recovery systems. Multiple member states have additional requirements including Germany, Netherlands, Ireland, Denmark, Belgium, and others.',
    cost: 0.08,
    policies: [mockPolicies[0], mockPolicies[1], mockPolicies[6], mockPolicies[7], mockPolicies[8], mockPolicies[9], mockPolicies[10], mockPolicies[13], mockPolicies[17]],
  },
  'germany': {
    answer: 'Germany has stringent efficiency standards for data centers. The German Waste Heat Recovery Act mandates that new data centers above 1MW must implement waste heat recovery systems and provide heat to local district heating networks, with a target of 60% heat recovery. Additionally, they must comply with the EU-wide directive requiring a PUE below 1.4 and 20% energy efficiency improvements.',
    cost: 0.06,
    policies: [mockPolicies[1], mockPolicies[0]],
  },
  'singapore': {
    answer: 'Singapore has established the Green Data Centre Standard which focuses on tropical climate optimization. Data centers must achieve a PUE below 1.3 and work towards 80% renewable energy usage by 2030. The standard emphasizes advanced cooling technologies suitable for hot and humid climates, promoting liquid cooling and free cooling techniques.',
    cost: 0.07,
    policies: [mockPolicies[2]],
  },
  'california': {
    answer: 'California has implemented data center energy conservation regulations through Title 24. These regulations require data centers to reduce water consumption (WUE < 1.2 L/kWh) and implement advanced cooling technologies. Data centers must utilize free cooling for at least 75% of the year and demonstrate significant reductions in environmental impact.',
    cost: 0.06,
    policies: [mockPolicies[3]],
  },
  'united states': {
    answer: 'The United States has various state-level policies for data center efficiency. California leads with strict energy conservation rules, Virginia requires performance reporting, and Texas offers tax incentives. Federal guidelines are primarily voluntary, with most regulation happening at the state level.',
    cost: 0.09,
    policies: [mockPolicies[3], mockPolicies[11], mockPolicies[19]],
  },
  'nordic': {
    answer: 'Nordic countries are leaders in waste heat utilization from data centers. Sweden, Norway, Finland, and Denmark have established programs to integrate data center waste heat into district heating networks. These countries leverage their cold climate for natural cooling while capturing waste heat for residential and commercial heating. Currently, several major data centers in Stockholm and Helsinki provide heat to thousands of homes.',
    cost: 0.09,
    policies: [mockPolicies[4], mockPolicies[14], mockPolicies[12], mockPolicies[21]],
  },
  'sweden': {
    answer: 'Sweden has progressive policies for data center waste heat integration with district heating networks. The Nordic District Heating Integration Directive requires data centers to supply at least 70% of their waste heat for residential use.',
    cost: 0.05,
    policies: [mockPolicies[4]],
  },
  'japan': {
    answer: 'Japan has set progressive PUE requirements for data centers as part of their Green IT initiative. New large-scale data centers must achieve a PUE of 1.3 or better, with incentives for facilities reaching 1.2 or below. The government also promotes the use of waste heat for nearby facilities and agricultural applications. Tokyo offers additional financial incentives for green data center technologies.',
    cost: 0.05,
    policies: [mockPolicies[5]],
  },
  'china': {
    answer: 'China has established a comprehensive national plan for data center energy efficiency. The five-year plan targets PUE below 1.3 for new facilities and aims for 30% improvement by 2029 through green cooling technologies and renewable energy adoption.',
    cost: 0.06,
    policies: [mockPolicies[18]],
  },
  'united kingdom': {
    answer: 'The UK offers grant funding for retrofitting existing data centers with advanced cooling and heat recovery technologies. The grant scheme provides £200M in funding to help facilities achieve PUE targets below 1.35.',
    cost: 0.05,
    policies: [mockPolicies[7]],
  },
  'uk': {
    answer: 'The UK offers grant funding for retrofitting existing data centers with advanced cooling and heat recovery technologies. The grant scheme provides £200M in funding to help facilities achieve PUE targets below 1.35.',
    cost: 0.05,
    policies: [mockPolicies[7]],
  },
  'canada': {
    answer: 'Canada provides voluntary best practices guidance for optimizing data center energy efficiency in cold climate regions. The guidance emphasizes year-round free cooling potential and recommends PUE below 1.3.',
    cost: 0.05,
    policies: [mockPolicies[10]],
  },
  'netherlands': {
    answer: 'The Netherlands offers tax credits for data center operators who supply waste heat to greenhouses and residential districts, with a 30% credit on heat recovery investments for facilities achieving minimum 50% heat reuse.',
    cost: 0.05,
    policies: [mockPolicies[6]],
  },
  'france': {
    answer: 'France has established a National Data Center Decarbonization Plan targeting carbon neutrality by 2030 through 80% waste heat recovery and 100% renewable energy for data center operations.',
    cost: 0.05,
    policies: [mockPolicies[8]],
  },
  'ireland': {
    answer: 'Ireland requires new hyperscale data centers to demonstrate viable heat reuse plans before receiving planning approval, with mandatory PUE targets below 1.4.',
    cost: 0.05,
    policies: [mockPolicies[9]],
  },
  'denmark': {
    answer: 'Denmark has established technical standards for liquid cooling systems and heat pump integration in data centers, requiring COP above 4.0 and enabling free cooling for 90% of the year.',
    cost: 0.05,
    policies: [mockPolicies[10]],
  },
  'finland': {
    answer: 'Finland operates a government platform connecting data center waste heat suppliers with district heating network operators, facilitating over 100MW of heat transfer with preferred quality above 60°C.',
    cost: 0.05,
    policies: [mockPolicies[12]],
  },
  'norway': {
    answer: 'Norway provides subsidies up to NOK 100M for data centers powered by hydroelectric energy with integrated waste heat recovery systems, requiring 100% renewable energy.',
    cost: 0.05,
    policies: [mockPolicies[14]],
  },
  'spain': {
    answer: 'Spain has regional regulations for water-scarce areas mandating dry cooling and heat recovery in new data centers, with heat recovery systems designed for desalination plants.',
    cost: 0.05,
    policies: [mockPolicies[15]],
  },
  'switzerland': {
    answer: 'Switzerland has established a national standard for measuring and reporting data center energy efficiency with PUE below 1.3 and mandatory ERE and CUE reporting.',
    cost: 0.05,
    policies: [mockPolicies[16]],
  },
  'belgium': {
    answer: 'The Brussels region requires data centers to connect to district heating networks where technically feasible, with mandatory connection within 500m and minimum 40% heat recovery.',
    cost: 0.05,
    policies: [mockPolicies[17]],
  },
  'austria': {
    answer: 'Austria offers grant programs totaling €50M for installing high-temperature heat pumps to upgrade waste heat quality for district heating, requiring heat output above 70°C.',
    cost: 0.05,
    policies: [mockPolicies[20]],
  },
  'iceland': {
    answer: 'Iceland provides best practice guidelines for integrating data center operations with geothermal energy systems, enabling natural cooling year-round with 100% renewable geothermal energy.',
    cost: 0.05,
    policies: [mockPolicies[21]],
  },
  'south korea': {
    answer: 'South Korea has launched a national initiative promoting AI-optimized cooling and waste heat utilization in data centers, targeting PUE below 1.3 through AI-driven optimization.',
    cost: 0.05,
    policies: [mockPolicies[22]],
  },
  'poland': {
    answer: 'Poland requires mandatory annual reporting of energy consumption, water use, and waste heat recovery rates for data centers over 500kW, including WUE and PUE disclosure.',
    cost: 0.05,
    policies: [mockPolicies[23]],
  },
  'virginia': {
    answer: 'Virginia has enacted state law requiring annual energy efficiency reporting and heat recovery feasibility studies for large data centers, with mandatory PUE disclosure.',
    cost: 0.05,
    policies: [mockPolicies[13]],
  },
  'texas': {
    answer: 'Texas offers property tax exemptions for data centers meeting high energy efficiency standards (PUE < 1.4) and using renewable energy, with up to 15-year tax exemption available.',
    cost: 0.05,
    policies: [mockPolicies[19]],
  },
  'default': {
    answer: 'I found several relevant policies based on your query. Data center heat utilization policies are evolving globally, with focus on energy efficiency, waste heat recovery, and integration with district heating systems. Key metrics include Power Usage Effectiveness (PUE), Water Usage Effectiveness (WUE), and heat recovery percentages. The search returned policies from multiple jurisdictions covering laws, regulations, directives, incentives, and standards.',
    cost: 0.12,
    policies: mockPolicies.slice(0, 10),
  },
};
